image: "python: 3.7"


stages:
  - Static Analysis
  - test
  - deploy


:
  stage: ver
  script:
      - python --version


test:
  stage: test
  script:
      - apt-get update -qy
      - apt-get install -y python-dev python-pip
      - pip install -r requirement.txt
      - python -m unittest discover --verbose . "*_test.py"
  only:
    gitlabci


deploy:
  stage: deploy
  script:
      - apt-get update -qy
  only:
    gitlabci

