image: "python: 3.7"

before_script:
  - python --version
  - pip install -r requirement.txt


stages:
  - analyze
  - test
  - deploy


pylint:
  stage: analyze
  allow_failure: true
  script:
      - pip install pylint --quiet
      - pylint --ignored -classs=_socketobject *.py


test:
  stage: test
  script:
      - pip install nose
      - python -m runtest xtest
      - pip install pytest --quiet
      - pytest


deploy:
  stage: deploy
  script:
      - echo "deploy"

